# Generated by Django 5.1.3 on 2024-11-05 08:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolso',
            fields=[
                ('id_bolso', models.AutoField(primary_key=True, serialize=False)),
                ('preciobolso', models.IntegerField()),
                ('fabricantebolso', models.TextField(max_length=50)),
                ('longitudcorrea', models.TextField(max_length=100)),
                ('materialbolso', models.TextField(choices=[('Cuero.', 'Cuero'), ('Tela.', 'Tela'), ('Plastico PVC', 'Plastico'), ('Lona.', 'Lona')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombreusuario', models.TextField(max_length=20)),
                ('telefonousuario', models.CharField(max_length=9)),
                ('direccion', models.TextField(max_length=30)),
                ('fecharegistrocuenta', models.DateTimeField(default=django.utils.timezone.now)),
                ('votante_adscrito', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaVotaciones',
            fields=[
                ('id_votacion', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion_proyecto', models.PositiveIntegerField()),
                ('comentario', models.TextField(max_length=300)),
                ('registrovotacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='examen.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id_cuentabancaria', models.AutoField(primary_key=True, serialize=False)),
                ('bancoasociado', models.TextField(choices=[('Caixa.', 'Caixa.'), ('BBVA', 'BBVA.'), ('UNICAJA', 'UNICAJA.'), ('ING', 'ING.')], max_length=10)),
                ('saldocuenta', models.FloatField(max_length=20)),
                ('titularcuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='examen.usuario')),
            ],
        ),
    ]
