# Generated by Django 5.1.3 on 2024-11-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemavotaciones',
            name='modelovotado',
            field=models.TextField(default='Bolso', max_length=10),
        ),
    ]
