# Generated by Django 5.1.3 on 2024-11-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0002_sistemavotaciones_modelovotado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='votante_adscrito',
            field=models.BooleanField(),
        ),
    ]
